language: node_js
node_js:
  - node
  - '8'
  - '6'
script:
  - npm run lint
  - npm test
jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run semantic-release
notifications:
  email: false
