service: python-tests

provider:
  name: aws
  runtime: python2.7

plugins:
  - './../../../index'

functions:
  hello:
    events:
      - http:
          method: get
          path: hello
    handler: handler.hello
