service: handler-payload-tests

provider:
  name: aws
  stage: dev
  region: us-east-1 # default
  runtime: nodejs10.x
  memorySize: 128
  versionFunctions: false

plugins:
  - './../../../index'

functions:
  # https://github.com/serverless/serverless/issues/4218#issue-255617750
  # bug?
  # - ${file(./handlerPayload.yml)}

  contextDoneHandler:
    name: 'contextDoneHandler'
    handler: handlerPayload.contextDoneHandler
    events:
      - http:
          method: get
          path: context-done-handler

  contextDoneHandlerDeferred:
    name: 'contextDoneHandlerDeferred'
    handler: handlerPayload.contextDoneHandlerDeferred
    events:
      - http:
          method: get
          path: context-done-handler-deferred

  contextSucceedHandler:
    name: 'contextSucceedHandler'
    handler: handlerPayload.contextSucceedHandler
    events:
      - http:
          method: get
          path: context-succeed-handler

  contextSucceedHandlerDeferred:
    name: 'contextSucceedHandlerDeferred'
    handler: handlerPayload.contextSucceedHandlerDeferred
    events:
      - http:
          method: get
          path: context-succeed-handler-deferred

  callbackHandler:
    name: 'callbackHandler'
    handler: handlerPayload.callbackHandler
    events:
      - http:
          method: get
          path: callback-handler

  callbackHandlerDeferred:
    name: 'callbackHandlerDeferred'
    handler: handlerPayload.callbackHandlerDeferred
    events:
      - http:
          method: get
          path: callback-handler-deferred

  promiseHandler:
    name: 'promiseHandler'
    handler: handlerPayload.promiseHandler
    events:
      - http:
          method: get
          path: promise-handler

  promiseHandlerDeferred:
    name: 'promiseHandlerDeferred'
    handler: handlerPayload.promiseHandlerDeferred
    events:
      - http:
          method: get
          path: promise-handler-deferred

  asyncFunctionHandler:
    name: 'asyncFunctionHandler'
    handler: handlerPayload.asyncFunctionHandler
    events:
      - http:
          method: get
          path: async-function-handler

  promiseWithDefinedCallbackHandler:
    name: 'promiseWithDefinedCallbackHandler'
    handler: handlerPayload.promiseWithDefinedCallbackHandler
    events:
      - http:
          method: get
          path: promise-with-defined-callback-handler

  contextSucceedWithContextDoneHandler:
    name: 'contextSucceedWithContextDoneHandler'
    handler: handlerPayload.contextSucceedWithContextDoneHandler
    events:
      - http:
          method: get
          path: context-succeed-with-context-done-handler

  callbackWithContextDoneHandler:
    name: 'callbackWithContextDoneHandler'
    handler: handlerPayload.callbackWithContextDoneHandler
    events:
      - http:
          method: get
          path: callback-with-context-done-handler

  callbackWithPromiseHandler:
    name: 'callbackWithPromiseHandler'
    handler: handlerPayload.callbackWithPromiseHandler
    events:
      - http:
          method: get
          path: callback-with-promise-handler

  callbackInsidePromiseHandler:
    name: 'callbackInsidePromiseHandler'
    handler: handlerPayload.callbackInsidePromiseHandler
    events:
      - http:
          method: get
          path: callback-inside-promise-handler
