service: ruby-tests

provider:
  name: aws
  runtime: ruby2.5

plugins:
  - './../../../index'

functions:
  hello:
    events:
      - http:
          method: get
          path: hello
    handler: handler.hello
